basic_settings:
  site_title: Lenia Margariti, PhD
  favicon_image: /images/faviconl2.png

header_settings:
  logo_image: 
  logo_width: 200

menu_settings:
  menu_items:
    - title: 'Projects'
      url: '/'
    # - title: 'Research'
    #   url: '/research/'
    # - title: 'Design'
    #   url: '/design/'
    - title: 'About'
      url: '/about'

footer_settings:
  logo_image: 
  logo_width: 200
  footer_tagline: 

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 30

contact_settings:
  form_action: ''
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  snapchat_url: ''
  youtube_url: ''
  google-plus_url: ''
  vimeo_url: ''
  pinterest_url: ''
  medium_url: ''
  quora_url: ''
  amazon_url: ''
  apple_url: ''
  android_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  deviantart_url: ''
  github_url: ''
  reddit_url: ''
  flickr_url: ''
  etsy_url: ''
  kickstarter_url: ''
  soundcloud_url: ''
  spotify_url: ''
  bandcamp_url: ''
  linkedin_url: ''

color_settings:
  background_color: '#ffffff'
  background_alt_color: '#f4f5f6'
  text_dark_color: '#2A2F36'
  text_medium_color: '#353a40'
  # text_medium_color: '#6C7A89'
  # text_medium_color: '#2A2F36'
  text_light_color: '#6C7A89'
  # text_light_color: '#ABB7B7'
  # accent_color: '#F2784B'
  accent_color: '#13a7d4'
  border_color: '#dddddd'
  # overlay_background_color: '#F2784B'
  overlay_background_color: '#13a7d4'
  # overlay_background_color: 'rgba(19, 167, 212)'
  # overlay_background_color: '#000000'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  font_embed: '<link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">'
  title_font: '"Muli", sans-serif'
  body_font: '"Muli", sans-serif'
  # font_embed: <link href="https://fonts.googleapis.com/css2?family=Ancizar+Sans:ital,wght@0,100..1000;1,100..1000&family=Mulish:ital,wght@0,200..1000;1,200..1000&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">  
  # title_font: '"Ancizar Sans", sans-serif'
  body_font: '"Mulish", sans-serif'
  title_font: '"Mulish", sans-serif'
  regular_weight: 400
  bold_weight: 600
  site_title:
    small_size: 25
    medium_size: 30
    large_size: 35
    weight: 300
    letter_spacing: -0.02
  menu:
    small_size: 30
    medium_size: 15
    large_size: 17
    weight: 350
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 700
    letter_spacing: -0.02
  grid_item_subtitle:
    extra_small_size: 12
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 700
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 35
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 600
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 700
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 15
    medium_size: 17
    large_size: 19
    weight: 400
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 15
    medium_size: 17
    large_size: 19
    # weight: 400
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 25
    medium_size: 35
    large_size: 45
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 400
    letter_spacing: 0

advanced_settings:
  ajax_loading: true
  analytics_code: ""
  custom_styles: ""
  header_js: ""
  footer_js: ""